### ISSUE TITLE
Needed developments in Tracker.match

### ISSUE THREAD

**Issue by giadarol** [xsuite/xsuite#285]
- [ ] Different steps for different knobs
 - [ ] Different scales for different targets
 - [ ] Target can be at assigned element
 - [ ] Ability to match a portion of the line

One of the goals it to be able to match the closed orbit at assigned locations

**Comment by giadarol** [comment]
Available in latest versions
