### ISSUE TITLE
Cleaner interface

### ISSUE THREAD

**Issue by giadarol** [xsuite/xsuite#78]
The following changes to the interface are being developed:
 - Remove the xline package
     - ```xline.Line``` becomes ```xtrack.Line```
     - instead of ```xline.Drift```, ```xline.Multipole``` etc. use directly ```xt.Drift```, ```xt.Multipole```
     - The Tracker objects are automatically updated when the line is modified (no need to regenerate the tracker)
 - There is only one Particles class within Xsuite
     - ```xline.Partices``` and ```xtrack.Particles``` to be replaced by ```xpart.Particles```
 - The reference python implementation of the main elements, which used to be in xline,  is moved to a small package called ```ducktrack``` to be used only for testing purposes (not part of normal tracking workflow)

**TODO:**
 - [x] Change xslowtrack to ducktrack
 - [x] Clean up names in examples and tests (xline, pysixtrack, xslowtrack --> ducktrack)
 - [x] Change ```assemble_particles``` to ```build_particles```
 - [x] Review dependencies in setup.py of all packages
 - [x] Re check test_data scripts
 - [x] Re-add json files
 - [x] Disable xline (raise error on import)
 - [x] Add some tests to xpart
 - [x] Run all tests
 - [x] Make pull requests
 - [x] Branch and adapt online documentation
 - [x] Update pymask
     - [x] further changes in Xtrack and Xpart (in separate branch)
     - [x] Profit to introduce line freeze after creating the tracker
     - [x] test and merge when done
 - [x] Merge!
 - [x] Change selected branches in sphynx conf.py

Here how I search:
```
git grep 'xline\|pysixtrack\|pyst\|xslowtrack\|xl' |grep -v xlim |grep -v xlabel|grep -v hxl
```

All packages are on branch ```feature/remove_python_particle```
